import { OnInit } from '@angular/core';
import { AbstractMenuProvider } from './menuProvider.service';
import { OverlayContainer } from '@angular/cdk/overlay';
import { MenuOption } from './models/MenuOption';
import { Router } from '@angular/router';
import { CanActivateRouteGuard } from '../security/can-activate-route.guard';
import { UserProfile } from '../user-manager/models/UserProfile';
import { UserProject } from '../user-manager/models/UserProject';
import { UserManagerService } from '../user-manager/user-manager.service';
import { LoggerService } from '../logger/logger.service';
export declare class LayoutComponent implements OnInit {
    private menuService;
    private userManagerService;
    private router;
    overlayContainer: OverlayContainer;
    private routeGuard;
    private log;
    componentCssClass: any;
    open: boolean;
    pinned: boolean;
    pinIcon: string;
    title: string;
    user: UserProfile;
    userProjects: UserProject[];
    currentProject: UserProject;
    menuItems: MenuOption[];
    constructor(menuService: AbstractMenuProvider, userManagerService: UserManagerService, router: Router, overlayContainer: OverlayContainer, routeGuard: CanActivateRouteGuard, log: LoggerService);
    ngOnInit(): void;
    setMenuOptionAccess(): void;
    onProjectChange(project: UserProject): void;
    getUserProfile(force?: boolean): void;
    setUserProfile(profile: UserProfile, force?: boolean): void;
    expand(): void;
    collapse(): void;
    togglePin(): void;
    logout(): void;
    onSetTheme(theme: any): void;
    switchProject(project: UserProject): void;
    setDefault(project: UserProject): void;
}
